const emoji = [
    "😂", "😂", "😂", "😂", "😂",
    "🤣", "🤣", "🤣", "🤣", "🤣",
    "🗿🍷",
    "💀", "💀", "💀", "💀", "💀",
    "☠️", "☠️", "☠️", "☠️", "☠️",
    "🍷🗿",
    "💔", "💔", "🥀", "🥀", "🥀", "🪫", "🪫", "🪫",
    "😭", "😭", "😭", "😭", "😭",
    "💀", "💀", "💀", "☠️", "☠️", "☠️", "😭", "😭", "😭",
    "😭🙏"
];

const brainrot = [
    "L",
    "skibidi toilet", "skibidi dop dop dop", "skibidi dop dop dop yes yes",
    "rizzler", "rizzard", "rizztraining order", "rizzing", "rizzing up", "rizz you up", "rizzonomics",
    "from ohio", "only in ohio",
    "based",
    "sigma",
    "sus", "sussy",
    "ice spice",
    "hawk tuah", "hawk tuah spit on that thang", "talk tuah", "talk tuah spit on that thang",
    "we're costco guys", "costco guys",
    "in the thick of it", "thick of it everybody knows",
    "youtube shorts",
    "zesty",
    "tiktok",
    "ts pmo",
    "diddy", "diddy party",
    "locked in alien",
    "ive played these games before",
    "no diddy",
    "mewing",
    "i like my cheese drippy bruh",
    "drippy cheese",
    "sturdy",
    "tiktok rizz party",
    "bomboclat",
    "friggin packet yo",
    "oi oi oi",
    "alpha",
    "looksmaxxing", "looksmax",
    "griddy",
    "livvy dunne", "livvy",
    "locked in", "lock in",
    "boom boom boom",
    "yap", "yapping", "yapper", "yapanese", "yapoholic",
    "drake",
    "brooooooooo",
    "one two buckle my shoe",
    "what's a father?",
    "fire in the hole",
    "blue tie kid",
    "quandale dingle", "quandale",
    "capping", "capanese", "capoholic",
    "put the fries in the bag",
    "turkish quandale",
    "low taper fade",
    "huzz",
    "glazing",
    "you know what else is massive",
    "chopped chin",
    "fortnite",
    "prime",
    "i bought a property in egypt",
    "eye of rah",
    "among us", "amogus",
    "giga chad", "chad",
    "water on the hill",
    "patrick bateman",
    "erm what the sigma",
    "+1000 aura", "aura",
    "chat is this real",
    "thugshaker", "thugshake",
    "costco guys",
    "john pork",
    "those who know 💀",
    "why so serious",
    "jonkler",
    "ocky way",
    "freakbob", "freaky",
    "let him cook",
    "baby gronk",
    "kai cenat",
    "still water",
    "caseoh",
    "english or spanish",
    "adin ross",
    "before gta 6",
    "roblox",
    "duke dennis",
    "monday left me broken",
    "mrbeast",
    "screaming in public restrooms prank",
    "gegagedigedagedago",
    "ambatukam",
    "freddy fazbear",
    "garten of banban",
    "oil up",
    "smurf cat",
    "fanum tax",
    "Nick Eh 30",
    "EDP445",
    "edge", "edging",
    "brainrot",
    "mango", "mango mango", "mango mango mango", "mango mango mango mango",
    "forgor",
    "mogwarts", "mogging", "mogger", "mogged",
    "womp womp",
    "pookie",
    "gooner", "gooning",
    "bombastic side eye",
    "grimace shake",
    "ishowspeed",
    "level 3 gyatt", "level 4 gyatt", "level 5 gyatt", "level 6 gyatt", "level 7 gyatt", "level 8 gyatt", "level 9 gyatt", "level 10 gyatt", "gyatt",
    "goofy ahh",
    "W"
];

const aliens = [
    "skibidi toilet",
    "ishowspeed",
    "caseoh",
    "grimace",
    "mrbeast",
    "drake",
    "duke dennis",
    "freddy fazbear",
    "adin ross",
    "Nick Eh 30",
    "locked in alien",
    "kai cenat",
    "oi larva",
    "john pork",
    "jonkler",
    "EDP445",
    "patrick bateman",
    "smurf cat",
    "ice spice",
    "huzz",
    "bro",
    "blud",
    "lil bro",
    "lil blud",
    "blue tie kid",
    "quandale dingle",
    "quandale",
    "gegagedigedagedago",
    "turkish quandale"
];

const yap = [
    "I had a",
    "and then",
    "so",
    "did a",
    "in a",
    "so then",
    "I saw a",
    "is",
    "was gonna",
    "caught lacking",
    "is cooked",
    "is joever",
    "is",
    "can we appreciate",
    "at the",
    "ts is",
    "but can we",
    "he was about to",
    "when I let",
    "and",
    "where you at",
    "lives in",
    "thinks he",
    "let him cook", "let him cook now",
    "is not",
    "never fails to",
    "am I",
    "is goated",
    "did you pray today",
    "I was in",
    "I became",
    "I have no",
    "when the"
];

function getRandomElement(array) {
    return array[Math.floor(Math.random() * array.length)];
}

function generateSentence() {
    const sentenceParts = [
        getRandomElement(aliens) + " " + getRandomElement(["is", "lives in", "thinks he", "is not", "never fails to"]),
        getRandomElement(yap) + " " + getRandomElement(brainrot),
        getRandomElement(yap) + " " + getRandomElement(aliens),
        getRandomElement(yap) + " " + getRandomElement(brainrot),
        getRandomElement(yap) + " " + getRandomElement(aliens)
    ];

    return sentenceParts.join(" ");
}

module.exports.generateOutput = () => {
    const sentence = generateSentence();
    const brainrotOutput = getRandomElement(brainrot);
    const emojiOutput = getRandomElement(emoji);

    return `${sentence} ${brainrotOutput} ${emojiOutput}`;
}